M48
; DRILL file {KiCad 8.0.8} date 2025-01-20T17:52:47-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-20T17:52:47-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X1.3189Y-2.9134
X2.2835Y-2.9134
T2
X1.811Y-1.9685
X2.311Y-1.9685
M30
